package com.dawes.modelo;
// Generated 30-nov-2017 17:42:21 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Titulares generated by hbm2java
 */
@Entity
@Table(name = "titulares", catalog = "banco", uniqueConstraints = @UniqueConstraint(columnNames = "nif"))
public class Titulares implements java.io.Serializable {

	private Integer idTitular;
	private String nombre;
	private String apellidos;
	private String direccion;
	private String poblacion;
	private String nif;
	private Date fechaNacimiento;
	private Double credito;
	private Set<Titularescuentas> titularescuentases = new HashSet<Titularescuentas>(0);

	public Titulares() {
	}

	public Titulares(String nombre, String apellidos, String direccion, String poblacion, String nif,
			Date fechaNacimiento, Double credito, Set<Titularescuentas> titularescuentases) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.nif = nif;
		this.fechaNacimiento = fechaNacimiento;
		this.credito = credito;
		this.titularescuentases = titularescuentases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTitular", unique = true, nullable = false)
	public Integer getIdTitular() {
		return this.idTitular;
	}

	public void setIdTitular(Integer idTitular) {
		this.idTitular = idTitular;
	}

	@Column(name = "nombre", length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", length = 45)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "direccion", length = 30)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "poblacion", length = 30)
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "nif", unique = true, length = 9)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "credito", precision = 22, scale = 0)
	public Double getCredito() {
		return this.credito;
	}

	public void setCredito(Double credito) {
		this.credito = credito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titulares")
	public Set<Titularescuentas> getTitularescuentases() {
		return this.titularescuentases;
	}

	public void setTitularescuentases(Set<Titularescuentas> titularescuentases) {
		this.titularescuentases = titularescuentases;
	}
	public void addTitularescuentas(Titularescuentas titularescuentas){
		titularescuentas.setTitulares(this);
		this.getTitularescuentases().add(titularescuentas);
	}

}
