package paquete;
// Generated 03-dic-2017 11:24:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name = "cuentas", catalog = "banco", uniqueConstraints = @UniqueConstraint(columnNames = "numCuenta"))
public class Cuentas implements java.io.Serializable {

	private Integer idCuenta;
	private String numCuenta;
	private Double saldo;
	private Date fecha;
	private Set titularescuentases = new HashSet(0);
	private Set movimientoses = new HashSet(0);

	public Cuentas() {
	}

	public Cuentas(String numCuenta, Double saldo, Date fecha, Set titularescuentases, Set movimientoses) {
		this.numCuenta = numCuenta;
		this.saldo = saldo;
		this.fecha = fecha;
		this.titularescuentases = titularescuentases;
		this.movimientoses = movimientoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCuenta", unique = true, nullable = false)
	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@Column(name = "numCuenta", unique = true, length = 20)
	public String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(String numCuenta) {
		this.numCuenta = numCuenta;
	}

	@Column(name = "saldo", precision = 22, scale = 0)
	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentas")
	public Set getTitularescuentases() {
		return this.titularescuentases;
	}

	public void setTitularescuentases(Set titularescuentases) {
		this.titularescuentases = titularescuentases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentas")
	public Set getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(Set movimientoses) {
		this.movimientoses = movimientoses;
	}

}
