package paquete;
// Generated 03-dic-2017 11:24:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titularescuentas generated by hbm2java
 */
@Entity
@Table(name = "titularescuentas", catalog = "banco")
public class Titularescuentas implements java.io.Serializable {

	private Integer idTitularCuenta;
	private Cuentas cuentas;
	private Titulares titulares;
	private Date fechaCreacion;

	public Titularescuentas() {
	}

	public Titularescuentas(Cuentas cuentas, Titulares titulares, Date fechaCreacion) {
		this.cuentas = cuentas;
		this.titulares = titulares;
		this.fechaCreacion = fechaCreacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTitularCuenta", unique = true, nullable = false)
	public Integer getIdTitularCuenta() {
		return this.idTitularCuenta;
	}

	public void setIdTitularCuenta(Integer idTitularCuenta) {
		this.idTitularCuenta = idTitularCuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCuenta")
	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTitular")
	public Titulares getTitulares() {
		return this.titulares;
	}

	public void setTitulares(Titulares titulares) {
		this.titulares = titulares;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaCreacion", length = 10)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

}
